services:
  web:
    image: qasim706/task-manager-app:latest
    container_name: flask_app_manual
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db_manual
      - DB_NAME=taskdb
      - DB_USER=taskuser
      - DB_PASSWORD=taskpass
    depends_on:
      db_manual:
        condition: service_healthy

  db_manual:
    image: postgres:14
    container_name: postgres_db_manual
    restart: always
    environment:
      POSTGRES_DB: taskdb
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpass
    volumes:
      - db_data_manual:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U taskuser"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data_manual:
